
// PRODUCT TYPES

export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const FETCHED_PRODUCT = "FETCHED_PRODUCT"
export const FETCHED_MORE_PRODUCT = "FETCHED_MORE_PRODUCT"


// ADMIN PRODUCTS TYPES

export const ADMIN_ADD_PRODUCTS = "ADMIN_ADD_PRODUCTS"
export const ADMIN_DELETE_PRODUCT = "ADMIN_DELETE_PRODUCT"
export const ADMIN_ADD_PRODUCT = "ADMIN_ADD_PRODUCT" 
export const ADMIN_TOGGLE_PROD_DISPLAY = "ADMIN_TOGGLE_PROD_DISPLAY"
export const ADMIN_DELETE_CATEGORY_FROM_PRODUCT = "ADMIN_DELETE_CATEGORY_FROM_PRODUCT"
export const ADMIN_ADD_CATEGORIES_TO_PRODUCT = "ADMIN_ADD_CATEGORIES_TO_PRODUCT"


// PRODUCTSINFO TYPES

export const ADD_PRODDUCTINFO = "ADD_PRODUCTINFO"


// ADMINSIDEBARTABS

export const INITIALIZE_TABS = "INITIALIZE_TABS"
export const TOGGLE_SUPPLIER_TAB = "TOGGLE_SUPPLIER_TAB"
export const TOGGLE_CATALOG_TAB = "TOGGLE_CATALOG_TAB"
export const TOGGLE_ORDERS_TAB = "TOGGLE_ORDERS_TAB"
export const TOGGLE_REPORTS_TAB = "TOGGLE_REPORTS_TAB"
export const TOGGLE_CUSTOMER_TAB = "TOGGLE_CUSTOMER_TAB"


// CART TYPES

export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const OPEN_CART = "OPEN_CART"
export const CLOSE_CART = "CLOSE_CART"
export const CLEAR_CART = "CLEAR_CART"

// WISHLIST TYPES

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST"
export const OPEN_WISHLIST = "OPEN_WISHLIST"
export const CLOSE_WISHLIST = "CLOSE_WISHLIST"
export const CLEAR_WISHLIST = "CLEAR_WISHLIST"


// COMPARE TYPES

export const ADD_TO_COMPARE = "ADD_TO_COMPARE"
export const DELETE_FROM_COMPARE = "DELETE_FROM_COMPARE"
export const OPEN_COMPARE = "OPEN_COMPARE"
export const CLOSE_COMPARE = "CLOSE_COMPARE"
export const CLEAR_COMPARE = "CLEAR_COMPARE"


// QUICK VIEW TYPES

export const OPEN_QUICK_VIEW = "OPEN_QUICK_VIEW"
export const CLOSE_QUICK_VIEW = "CLOSE_QUICK_VIEW"

// FILTERS TYPES

export const UPDATE_PRODUCT_FILTERS = "UPDATE_PRODUCT_FILTERS"
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY"
export const UPDATE_RATING = 'UPDATE_RATING'

//  LOGIN MODAL

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL"
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL"

// LOCAL STORAGE

export const INIT_LOCALSTORAGE = "INIT_LOCALSTORAGE"

//CATEGORIES

export const ADD_CATEGORIES = "ADD_CATEGORIES"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"